# ibm-semeru-runtimes@sha256:31aa50f23d688068e54ca413876f7c01fbb83aa81766f85de56b3e23aa36ba8b
# 0.29.1
from ibm-semeru-runtimes:open-17-jdk as jdk17

from node:16

COPY --from=jdk17 /opt/java/openjdk /opt/java/openjdk

RUN ln -s /opt/java/openjdk/bin/j* /usr/bin/
