# ibm-semeru-runtimes@sha256:bfa0fb8d2d1ed8e82cfc38b4ab143068302d995e77a037399febebf6b1ed82c6
# 0.29.1
from ibm-semeru-runtimes:open-8-jdk as jdk8

from node:16

COPY --from=jdk8 /opt/java/openjdk /opt/java/openjdk

RUN ln -s /opt/java/openjdk/bin/j* /usr/bin/
