# ibm-semeru-runtimes@sha256:ff711164e8a3c20c9fc761ce56b499ff0fe1cd88b6927fd3e632f459032909cf
# 0.29.1
from ibm-semeru-runtimes:open-11-jdk as jdk11

from node:16

COPY --from=jdk11 /opt/java/openjdk /opt/java/openjdk

RUN ln -s /opt/java/openjdk/bin/j* /usr/bin/
